name: Validate links on push + PR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v6.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Validate links
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          # Check all MD files, ignore ok/redir/blocked/rate-limited, exclude commonly down domains
          args: >-
            "*.md" "**/*.md"
            --verbose --no-progress --include-mail
            --include-fragments --index-files README.md --exclude "#readme"
            --accept 200..299,300..399,403,429
            --cache --max-cache-age 3d
            --exclude api\.star-history\.com --exclude browser\.qq\.com --exclude ghostbrowser\.com --exclude openuserjs\.org
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Save lychee cache
        uses: actions/cache/save@v6.1.0
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
